### ISSUE TITLE
无法使用，保持 ENOTFOUND & ECONNREFUSED

### ISSUE THREAD

**Issue by leizongmin** [Lellansin/node-net-scan#1]
执行扫描时报错：

扫描域名，报错`ENOTFOUND`

```
$ scan -h baidu.com -r 1~1000
scan host: baidu.com ports 1~1000
port 80 is open
scanning [                    ] 0% 1/1000   port 443 is open
scanning [                    ] 0% 2/1000   events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND baidu.com baidu.com:511
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

扫描IP地址，报错`ECONNREFUSED`

```
$ scan -h 120.25.100.226 -r 1~1000
scan host: 120.25.100.226 ports 1~1000
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 120.25.100.226:1
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```

当然使用README中的示例是可以的：

```
$ scan -h github.com -r 1~1000
scan host: github.com ports 1~1000
port 22 is open
scanning [                    ] 0% 1/1000   port 80 is open
scanning [                    ] 0% 2/1000   port 443 is open
scanning [====================] 100% 1000/1000
ports scan: 5820ms
open ports: [ 22, 80, 443 ]
```

系统环境：

```
$ scan -V
0.1.0

$ node -v
v4.3.0

Node版本
  versions:
   { http_parser: '2.5.1',
     node: '4.3.0',
     v8: '4.5.103.35',
     uv: '1.8.0',
     zlib: '1.2.8',
     ares: '1.10.1-DEV',
     icu: '56.1',
     modules: '46',
     openssl: '1.0.2f' },
  arch: 'x64',
  platform: 'darwin',
```

**Comment by Lellansin** [comment]
_(:3 」∠)_  已修复，等会有空再优化下。。
